spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Dau Ngoc Minh Anh - Developer"
    email: "minhanh@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345